### PR TITLE
First module add

### PR DESCRIPTION
**Pull request by itdependsnetworks**
Would require: https://github.com/infobloxopen/infoblox-client/pull/170 to be pushed to work for comments

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
First module, so wanted to get consensus before  going further.

**Comment by johnbelamaric** [comment]
@brampling please take a look. I have zero Ansible knowledge. I will make @brampling and @itdependsnetworks commiters for this repo...

**Comment by itdependsnetworks** [comment]
Thanks. Will defer for the first merge, in the interest of consensus.

**Comment by brampling** [comment]
@itdependsnetworks Is the plan to keep network and host operations in separate modules? We may also want another module for admin operations later.

**Comment by itdependsnetworks** [comment]
Yes, I would think a rough breakdown.

HOST 
A 
PTR 
CNAME
SRV
Auth Zone

With additional get next abilities were applicable.

**Pull request merged**
