### PR TITLE
Add modules to manipulate DTC objects

### PR DESCRIPTION
**Pull request by badnetmask**
This PR adds support to manipulate DTC(*) objects.

I have not implemented every single option and operation that the API permits, but this is the minimum necessary to have a GSLB.

Each module's documentation contain examples.

I am still working to implement more objects and options, but I would like to start the code review right away, and slowly work on adding the other things later.

* DTC = Infoblox DNS Traffic Control, i.e. GSLB (Global Service Load Balancing).

### CODE REVIEW

**Comment by badnetmask** [comment]
Regarding the CI validation: I was able to make the necessary changes for PEP8, but now it's failing on `validate-modules`, and I am unable to see exactly what is causing the failure. Even running the commands on my own system do not give the same message. Any pointers would be appreciated.

**Comment by badnetmask** [comment]
Looks like all CI checks passed, so this is ready for review. Thank you.

**Comment by badnetmask** [comment]
I had to write a new module to restart services, otherwise manipulating DTC objects would result in a weird status in the grid.

**Comment by ciobancai** [comment]
Hi, we would know on when this MR will be merged and to be used ?

**Comment by badnetmask** [comment]
> Hi, we would know on when this MR will be merged and to be used ?

Unfortunately I don't know how often the Infoblox team review pull requests. Sorry.

**Comment by badnetmask** [comment]
@Vaishnavi-infoblox @saileshgiri -- Hi. I would like to ask what can we do to move forward with this PR. Thank you.

**Review by anagha-infoblox — APPROVED** [review]

**Pull request merged**
