### PR TITLE
Added sanity fix for missing arg spec type and/or

### PR DESCRIPTION
**Pull request by anshulbehl**
- missing type in documentation
- Added ignore file for plugins/modules/nios_nsgroup.py

### CODE REVIEW

**Comment by anshulbehl** [comment]
@Vaishnavi-infoblox I have added the ignore for `plugins/modules/nios_nsgroup.py` as the documentation for that file is getting generated programatically and it would be difficult to fix
also added other fix so it helps you understand the missing type in argspec or missing type in doc errors

**Comment by anshulbehl** [comment]
Also the 2.9 job got cancelled because 2.10 failed, can you switch the order in the workflows file to check the same

**Comment by Vaishnavi-infoblox** [comment]
Hi @anshulbehl ,

I have merged your yesterday's Pull request and changed python version 2.7 and stable ansible version to 2.9 in workflows/ansible-test.yml and these are the latest errors - https://github.com/infobloxopen/infoblox-ansible/runs/1085172244 in python 2.7 there are no errors but it exists in python 3.7 version. Please let us know your thoughts

**Comment by anshulbehl** [comment]
@Vaishnavi-infoblox All the issues can be fixed by fixes I sent out in this pull request, you just need to check which ones are type mismatch and fix them in the module files, these error are related to python 3.7 as it is the one that runs the validate-modules sanity test.
Let me know if you need help fixing these issues

**Pull request merged**
