### PR TITLE
added ddns_protected support

### PR DESCRIPTION
**Pull request by xdkreij**
Herewith the suggestion to add the ddns protected feature towards the infoblox host record module. 
We've seen a couple of cases where ddns starts to overwrite the created host record after a while, this feature provides the capability to protect the record from being overwritten.

Kind regards,

Xdk

### CODE REVIEW

**Review by hemanthKa677 — COMMENTED** [review]
Can you please provide us the working example to test this changes?

**Comment by xdkreij** [comment]
> Can you please provide us the working example to test this changes?

lol - only 2 years later..

regardless; Visit <[link](https://github.com/xdkreij/infoblox-ansible/blob/master/ansible_collection/infoblox/nios_modules/plugins/modules/nios_host_record.py for the actual DDNS change.)>

        ddns_protected=dict(type='bool', default=False, required=False),

**Comment by edeka-spatt** [comment]
Please merge this request, i need the same feature.

**Review by hemanthKa677 — COMMENTED** [review]
Hi @xdkreij , Can you please check with conflict raising with file? So that we can merge this asap.

**Comment by xdkreij** [comment]
> Hi @xdkreij , Can you please check with conflict raising with file? So that we can merge this asap.

Merged my fork with the infoblox-ansible repository; It should be up 2 date, kindly review.

**Comment by xdkreij** [comment]
visit https://github.com/infobloxopen/infoblox-ansible/pull/169 for new up2date request

**Pull request closed without merging**
