### PR TITLE
Fixing validate-modules sanity test failures

### PR DESCRIPTION
**Pull request by anshulbehl**
@Vaishnavi-infoblox  I have tried to fix a lot of validate-module failures and added the doc_fragment at the right place
as well as added some missing parameters in spec, whose description you will probably need to add

Can you review and accept the same accordingly

cc: @@felixfontein

### CODE REVIEW

**Comment by anshulbehl** [comment]
@Vaishnavi-infoblox you can also add sanity ignore files to ignore validate-modules failures that do not affect the functioning of your collection
example: https://github.com/ansible-collections/vyos.vyos/blob/main/tests/sanity/ignore-2.9.txt
https://github.com/ansible-collections/vyos.vyos/blob/main/tests/sanity/ignore-2.10.txt

Documentation: https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/ignores.html

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
Adding ignore.txt is only a shortgap measure, these things need to get fixed sooner or later. (The huge amount of sanity errors is also a result of ignore.txt entries accumulating over time in ansible/ansible.)

Some things that should definitely **not** be ignored are the version_added failures. It's best to remove all `version_added` fields which contain Ansible versions.

@Vaishnavi-infoblox BTW it would also be helpful if you could create a PR for your branch (f.ex. after merging this into your branch), so that it is possible to add comments to your changes directly.

**Comment by Vaishnavi-infoblox** [comment]
Thank you @anshulbehl and @felixfontein the above information is really helpful, I will do the same and let you know.

**Comment by Vaishnavi-infoblox** [comment]
I have created a new PR for my branch and added 5 lines in ignore.txt(just to test) but still those 5 errors are in sanity. Please review my PR - https://github.com/infobloxopen/infoblox-ansible/pull/13

**Pull request merged**
