### PR TITLE
Adding the two options to Ipv4 to allow PXE server configuration

### PR DESCRIPTION
**Pull request by Medalibi**

### CODE REVIEW

**Comment by matthewdennett** [comment]
Hi @Medalibi, I hope you can get some traction with this change. This is going to be very useful once it gets merged and released.

**Comment by ranjishmp** [comment]
Some UTs a failing.. Can you please clear them out?

**Comment by matthewdennett** [comment]
Hi @Medalibi, is this PR addressing issue #94? If that is the case it might be worth mentioning in the PR description.

**Comment by Medalibi** [comment]
Hi @matthewdennett, it is addressing a portion of it but not the whole thing. I was able to find the two options pxe and use_pxe on the Infoblox documentation. As for the other options, I am not very sure. In my view, addressing this is already very good as those other configs can be set from the pxe server level, which is what I already do from within my environment.

**Review by hemanthKa677 — COMMENTED** [review]
@Medalibi , Can you please share us example for testing this feature?

**Review by JkhatriInfobox — APPROVED** [review]
Changes looks good for supporting nextserver parameter.

**Pull request merged**
