### PR TITLE
Add support for member assignment to nios_network

### PR DESCRIPTION
**Pull request by matthewdennett**
This PR aims to provide the support for member assignment during the creation of a network with the niso_network module. 

To support this change  'convert_members_to_struct(member_spec)' has been added to 'module_utils/api.py' that transforms the ansible input into the correct data structure required for the API endpoint. With this transformation the existing process can now successfully create the member assignment and update the assignment if needed. 

- Doco in nios_network.py updated with the definition of the members option
- Example in nios_network.py has been updated with a new example

This will address feature request:
- https://github.com/infobloxopen/infoblox-ansible/issues/69

### CODE REVIEW

**Comment by matthewdennett** [comment]
Hi @anagha-infoblox, are you able to recommend what needs to be done next to progress this PR?

**Comment by matthewdennett** [comment]
Hi @anaghakh4, are you able to have a look at this one and review please?

**Comment by ranjishmp** [comment]
Hi @matthewdennett 

Seems this PR will conflict with https://github.com/infobloxopen/infoblox-ansible/pull/151. Do we need to consider both ? if yes can you please combine them both and raise a new PR ?

**Comment by matthewdennett** [comment]
Hi @ranjishmp 

The two PRs shouldn't conflict unless I have left something in one that's shouldn't be there. Can you list which parts will conflict? 

I'm happy to put them together as a single PR if that's needed. 

Cheers.

**Comment by ranjishmp** [comment]
Both PR contains same member field added. Also for def convert_range_member_to_struct(member_spec) in api.py file function is common.

**Comment by matthewdennett** [comment]
I have definitely mixed something up between the two PRs. I should have some time this afternoon to fix it up and resolve the conflicting code.

**Comment by matthewdennett** [comment]
Hey @ranjishmp 

I have fixed up the overlapping code. Looks like I hadn't cleaned up correctly between working on each branch. The issues should be resolved now and the PRs independent of each other. 

It's worth noting that this PR adds ```def convert_members_to_struct(member_spec): ``` and PR #151 adds ```def convert_range_member_to_struct(member_spec):``` which might have been seen as the same function. If the names are too similar I'm happy to update them for further clarity and readability of the code.

**Comment by matthewdennett** [comment]
As requested by @hemanthKa677 this PR is being closed. The changes have been submitted as part of PR #152

**Pull request closed without merging**
